// Strategy Library — sourced from 85 Tax Strategies PDF and roadmap examples
// Each strategy has: id, name, description, savingsMin, savingsMax, irsRefs, 
// applicableTo (entity types), triggerConditions (what data points must be present)

export type EntityType = "1040" | "1120S" | "1065" | "C-Corp" | "1120";
export type TriggerKey = 
  | "has_wages" | "has_business_income" | "has_net_profit" | "business_net_profit_over_100k"
  | "business_net_profit_over_50k" | "has_employees" | "has_non_owner_employees"
  | "has_mortgage_interest" | "has_ira_distributions" | "has_capital_gains"
  | "has_charitable_donations" | "agi_over_150k" | "agi_over_400k" | "has_dependents"
  | "dependents_have_earned_income" | "has_home_office_expense" | "has_vehicle_expense"
  | "has_travel_expense" | "has_meals_expense" | "has_rental_income" | "has_real_estate"
  | "is_partnership_or_schedule_c" | "is_s_corp" | "is_c_corp" | "already_has_retirement_plan"
  | "has_business_vehicle_purchase" | "salt_at_limit" | "has_medical_expenses"
  | "has_passive_income" | "has_long_term_capital_gains" | "business_has_loss"
  | "has_health_insurance_personal" | "has_inventory" | "has_tips_paid" | "has_real_property";

export interface Strategy {
  id: string;
  name: string;
  shortDescription: string;
  longDescription: string;
  savingsMin: number;
  savingsMax: number;
  irsRefs: string;
  applicableEntityTypes: EntityType[];
  // Conditions that SUGGEST this strategy (recommend if these are present)
  triggerOn: TriggerKey[];
  // Conditions that EXCLUDE this strategy
  excludeIf: TriggerKey[];
  category: string;
}

export const STRATEGIES: Strategy[] = [
  // =================== INDIVIDUAL (1040) STRATEGIES ===================
  {
    id: "augusta_rule",
    name: "Augusta Rule",
    shortDescription: "Rent your home for up to 14 days annually, tax-free.",
    longDescription: "The IRS allows a business owner to rent their primary residence or vacation home to their business for up to 14 non-consecutive days each year. Income is excluded from taxable income under IRC Section 280A.",
    savingsMin: 1000,
    savingsMax: 15000,
    irsRefs: "PLR 8104117, IRC Section 280A, IRC Section 274(a)(1)(B), IRC Section 162, Rev. Rul. 76-287",
    applicableEntityTypes: ["1040", "1120S", "1065"],
    triggerOn: ["has_business_income"],
    excludeIf: ["has_rental_income"],
    category: "Legal Loopholes",
  },
  {
    id: "itemized_deductions",
    name: "Itemized Deductions",
    shortDescription: "Deduct eligible expenses like mortgage interest and charitable donations to reduce taxable income.",
    longDescription: "Itemizing deductions is advantageous when total eligible expenses (mortgage interest, state/local taxes capped at $10K, medical expenses over 7.5% of AGI, charitable donations) exceed the standard deduction. Most beneficial for homeowners in high-tax states with significant medical or charitable expenses.",
    savingsMin: 2000,
    savingsMax: 10000,
    irsRefs: "IRC 63, IRC 67, IRC 68, IRC 164, IRC 163, IRC 170, IRC 213, Rev. Proc. 2023-34, TCJA Itemized Deduction Changes Guide",
    applicableEntityTypes: ["1040"],
    triggerOn: ["has_mortgage_interest", "salt_at_limit"],
    excludeIf: [],
    category: "Maximize Deductions",
  },
  {
    id: "oil_and_gas",
    name: "Oil and Gas",
    shortDescription: "Tax benefits and energy market exposure through oil and gas investments, with associated risks.",
    longDescription: "Oil and gas investments offer significant tax advantages including intangible drilling cost deductions (often 70-80% of investment in year one), depletion allowances, and passive income offset opportunities. Best for high-income taxpayers seeking to reduce ordinary income.",
    savingsMin: 10000,
    savingsMax: 50000,
    irsRefs: "26 U.S.C. 43, 26 U.S.C. 613/613A, 26 U.S.C. 263(c), 26 U.S.C. 199A, IRS Publication 535",
    applicableEntityTypes: ["1040"],
    triggerOn: ["agi_over_150k", "has_passive_income"],
    excludeIf: [],
    category: "Niche Strategies",
  },
  {
    id: "qcds",
    name: "Qualified Charitable Distributions",
    shortDescription: "Transfer funds directly from your IRA to charity tax-free, satisfying required minimum distributions.",
    longDescription: "Taxpayers age 70½ or older can transfer up to $100,000 per year directly from an IRA to a qualified charity, reducing taxable income and satisfying RMD requirements. Particularly valuable when charitable deductions would otherwise be limited.",
    savingsMin: 1000,
    savingsMax: 12000,
    irsRefs: "IRC Section 408(d)(8), IRC Section 170(b)(1)(A), IRS Notice 2007-7, Pension Protection Act of 2006, SECURE Act and SECURE 2.0",
    applicableEntityTypes: ["1040"],
    triggerOn: ["has_ira_distributions"],
    excludeIf: [],
    category: "Retirement Planning",
  },
  {
    id: "sell_your_home",
    name: "Sell Your Home",
    shortDescription: "Exclude major portion of home sale profits from taxes, if eligibility criteria are met.",
    longDescription: "Homeowners who have lived in their primary residence for at least 2 of the past 5 years can exclude up to $250,000 ($500,000 MFJ) of capital gains from sale. This exclusion resets every 2 years and is one of the most powerful tax-free wealth-building strategies available.",
    savingsMin: 15000,
    savingsMax: 75000,
    irsRefs: "26 U.S.C. 121, Taxpayer Relief Act of 1997, 26 C.F.R. 1.121-1, IRS Publication 523, IRS Topic no. 701",
    applicableEntityTypes: ["1040"],
    triggerOn: ["has_mortgage_interest"],
    excludeIf: [],
    category: "Exits & Capital Gains",
  },
  {
    id: "tax_loss_harvesting",
    name: "Tax Loss Harvesting",
    shortDescription: "Sell losing investments to offset gains and reduce capital gains taxes owed.",
    longDescription: "Strategically selling securities at a loss to offset capital gains and up to $3,000 of ordinary income per year. Losses in excess of $3,000 carry forward to future years. Most effective for investors with significant unrealized losses and capital gains in the same tax year.",
    savingsMin: 2000,
    savingsMax: 20000,
    irsRefs: "IRC Sections 1211, 1212, 1091, 1222, 165, IRS Publications 550 and 544, Form 8949, Schedule D",
    applicableEntityTypes: ["1040"],
    triggerOn: ["has_capital_gains"],
    excludeIf: [],
    category: "Advanced Strategies",
  },
  {
    id: "traditional_401k_individual",
    name: "Traditional 401k",
    shortDescription: "A retirement account where you skip taxes now and pay them when you withdraw the money in retirement.",
    longDescription: "Pre-tax contributions to a traditional 401(k) reduce taxable income dollar-for-dollar, up to $23,000 (2024) plus $7,500 catch-up if age 50+. Particularly valuable for taxpayers in higher tax brackets who expect to be in a lower bracket in retirement.",
    savingsMin: 1000,
    savingsMax: 22570,
    irsRefs: "26 U.S.C. 401(a), 26 U.S.C. 402(g), 26 U.S.C. 219, IRS Publication 560, IRS Publication 590-A/B, SECURE 2.0 Act",
    applicableEntityTypes: ["1040"],
    triggerOn: ["has_wages"],
    excludeIf: [],
    category: "Retirement Planning",
  },
  {
    id: "roth_401k_individual",
    name: "Roth 401k (Individual)",
    shortDescription: "A retirement account where you pay taxes now so you can withdraw the money tax-free in retirement.",
    longDescription: "After-tax Roth 401(k) contributions grow tax-free and qualified withdrawals are tax-free. Best for taxpayers who expect higher tax rates in retirement or want tax diversification. Can be combined with traditional 401(k) contributions up to the annual limit.",
    savingsMin: 0,
    savingsMax: 22570,
    irsRefs: "26 U.S.C. 402A, IRS Notice 2024-02, SECURE 2.0 Act 604, IRS Publication 590-B",
    applicableEntityTypes: ["1040"],
    triggerOn: ["has_wages"],
    excludeIf: [],
    category: "Retirement Planning",
  },
  {
    id: "child_tax_credit",
    name: "Child Tax Credit",
    shortDescription: "Tax savings through the Child Tax Credit, subject to IRS rules.",
    longDescription: "Provides up to $2,000 per qualifying child under age 17. Subject to phase-out above $400,000 AGI (MFJ). Partially refundable (up to $1,600). Should be reviewed annually for eligibility and optimization opportunities.",
    savingsMin: 500,
    savingsMax: 5000,
    irsRefs: "IRC 24, IRC 152, IRC 32, Schedule 8812, Pub. L. No. 115-97 (TCJA), IRS Publication 972",
    applicableEntityTypes: ["1040"],
    triggerOn: ["has_dependents"],
    excludeIf: ["agi_over_400k"],
    category: "Tax Credits",
  },
  {
    id: "child_roth_ira",
    name: "Child Roth IRA",
    shortDescription: "A custodial retirement account allowing minors with earned income to make after-tax contributions that grow tax-free.",
    longDescription: "Children with earned income can contribute to a Roth IRA (up to the lesser of earned income or the annual limit). Tax-free compound growth over decades makes this one of the most powerful long-term wealth-building strategies for families.",
    savingsMin: 500,
    savingsMax: 7000,
    irsRefs: "IRC Section 408A, IRC Section 219, IRS Retirement Plans FAQs Regarding IRAs, IRS Publication 590-A",
    applicableEntityTypes: ["1040"],
    triggerOn: ["has_dependents", "dependents_have_earned_income"],
    excludeIf: [],
    category: "Retirement Planning",
  },
  {
    id: "qsbs",
    name: "QSBS: Small Business Stock Sales",
    shortDescription: "Hold small business stock for 5+ years to avoid paying taxes on up to $10 million in profits when you sell.",
    longDescription: "Section 1202 allows taxpayers to exclude 100% of capital gains (up to $10M or 10x cost basis) from the sale of Qualified Small Business Stock held for more than 5 years. The stock must be in a domestic C corporation with gross assets under $50M at time of issuance.",
    savingsMin: 2000,
    savingsMax: 20000,
    irsRefs: "IRC Section 1202, IRC Section 1045, IRC Section 1244, IRS Publication 550, Revenue Ruling 2018-27",
    applicableEntityTypes: ["1040"],
    triggerOn: ["has_long_term_capital_gains", "has_passive_income"],
    excludeIf: [],
    category: "Exits & Capital Gains",
  },
  {
    id: "health_savings_account",
    name: "Health Savings Account (HSA)",
    shortDescription: "Save pre-tax money for qualified medical expenses, reducing your out-of-pocket healthcare costs.",
    longDescription: "Triple tax advantage: contributions are pre-tax, growth is tax-free, and qualified medical expense withdrawals are tax-free. Must be enrolled in a High Deductible Health Plan. 2024 contribution limits: $4,150 single / $8,300 family, plus $1,000 catch-up if 55+.",
    savingsMin: 1000,
    savingsMax: 8300,
    irsRefs: "26 U.S.C. 223, 26 C.F.R. 1.223-1 to 1.223-3, IRS Form 8889, IRS Publication 969",
    applicableEntityTypes: ["1040"],
    triggerOn: ["has_medical_expenses", "has_health_insurance_personal"],
    excludeIf: [],
    category: "Insurance",
  },

  // =================== BUSINESS (S-CORP, PARTNERSHIP, C-CORP) STRATEGIES ===================
  {
    id: "accountable_plan",
    name: "Accountable Plan",
    shortDescription: "Allows business owners to reimburse employee expenses tax-free while reducing payroll and income taxes.",
    longDescription: "A formal written reimbursement policy that allows the business to reimburse owners/employees for business expenses (home office, vehicle, phone, etc.) tax-free. Reduces both payroll taxes and income taxes. Especially valuable for S-Corp owner-employees.",
    savingsMin: 10000,
    savingsMax: 35000,
    irsRefs: "IRC 62(c), IRC 162(a), IRC 274(d), IRC 3121(a)(2)(A), Treas. Reg. 1.62-2, IRS Publication 463",
    applicableEntityTypes: ["1120S", "1065", "C-Corp"],
    triggerOn: ["has_business_income", "has_net_profit"],
    excludeIf: [],
    category: "Maximize Deductions",
  },
  {
    id: "home_office",
    name: "Home Office",
    shortDescription: "Tax deductions for dedicated business space in your home.",
    longDescription: "Business owners using a dedicated area of their home exclusively and regularly for business can deduct a proportional share of home expenses. S-Corp owners should use an accountable plan to reimburse home office expenses from the business. Partnerships can also qualify.",
    savingsMin: 1000,
    savingsMax: 5000,
    irsRefs: "26 U.S.C. 280A, IRS Form 8829, IRS Publication 587, Revenue Procedure 2013-13, Commissioner v. Soliman, 506 U.S. 168",
    applicableEntityTypes: ["1120S", "1065", "1040"],
    triggerOn: ["has_business_income"],
    excludeIf: [],
    category: "Maximize Deductions",
  },
  {
    id: "meals",
    name: "Meals",
    shortDescription: "50% tax deduction on business-related meals, with some 100% exceptions.",
    longDescription: "Business meals with clients, employees, or business associates are 50% deductible. Employer-provided meals on business premises for business convenience may be 100% deductible. Proper documentation (business purpose, attendees, amount) is required.",
    savingsMin: 500,
    savingsMax: 10000,
    irsRefs: "26 U.S.C. 274, 26 U.S.C. 162(a), 26 U.S.C. 274(k), Notice 2018-76, IRS Publication 463",
    applicableEntityTypes: ["1120S", "1065", "C-Corp", "1040"],
    triggerOn: ["has_business_income"],
    excludeIf: [],
    category: "Maximize Deductions",
  },
  {
    id: "travel",
    name: "Travel",
    shortDescription: "Tax deductions for necessary business travel expenses.",
    longDescription: "Ordinary and necessary business travel expenses away from home (airfare, hotel, 50% of meals, transportation) are fully deductible. Travel must have a primary business purpose. Mixed business/personal trips require allocation. Documentation is critical.",
    savingsMin: 2000,
    savingsMax: 10000,
    irsRefs: "26 U.S.C. 162(a), 26 U.S.C. 274(d), 26 C.F.R. 1.162-2, IRS Publication 463, Revenue Procedure 2019-48",
    applicableEntityTypes: ["1120S", "1065", "C-Corp", "1040"],
    triggerOn: ["has_business_income", "has_travel_expense"],
    excludeIf: [],
    category: "Maximize Deductions",
  },
  {
    id: "vehicle",
    name: "Vehicle",
    shortDescription: "Tax deductions for business use of personal or company vehicles.",
    longDescription: "Business vehicle expenses can be deducted using actual expenses (depreciation, fuel, insurance, repairs) or standard mileage rate (67¢/mile for 2024). SUVs and trucks over 6,000 lbs GVW may qualify for accelerated Section 179 expensing. Detailed mileage logs are required.",
    savingsMin: 3000,
    savingsMax: 10000,
    irsRefs: "26 U.S.C. 179, 26 U.S.C. 280F, 26 U.S.C. 162(a), 26 U.S.C. 274(d), IRS Form 4562, IRS Publication 463",
    applicableEntityTypes: ["1120S", "1065", "C-Corp", "1040"],
    triggerOn: ["has_vehicle_expense", "has_business_income"],
    excludeIf: [],
    category: "Maximize Deductions",
  },
  {
    id: "hiring_kids",
    name: "Hiring Your Children",
    shortDescription: "Tax savings through hiring children in family businesses, subject to IRS rules.",
    longDescription: "Children under 18 employed by a parent's sole proprietorship or partnership are exempt from FICA taxes. Wages paid are deductible by the business and shift income to the child's lower tax bracket. Children can contribute earnings to a Roth IRA. Wages must be reasonable for actual work performed.",
    savingsMin: 3000,
    savingsMax: 15000,
    irsRefs: "26 U.S.C. 3121(b)(3)(A), 26 U.S.C. 3306(c)(5), IRC Section 152(c), IRS Publication 929, IRS Publication 535",
    applicableEntityTypes: ["1120S", "1065", "1040"],
    triggerOn: ["has_dependents"],
    excludeIf: [],
    category: "Maximize Deductions",
  },
  {
    id: "traditional_401k_business",
    name: "Traditional 401k (Business)",
    shortDescription: "An employee-based retirement plan with pre-tax contributions and tax-deferred growth for retirement.",
    longDescription: "Business-sponsored 401(k) plans allow employee and employer contributions. Employer contributions are deductible. For owner-employees of profitable businesses, combining employee deferrals with profit-sharing contributions can shelter significant income from taxes. Pairs well with Safe Harbor provisions to maximize owner benefits.",
    savingsMin: 2100,
    savingsMax: 52500,
    irsRefs: "26 U.S.C. 401(a), 26 U.S.C. 402(g), 26 U.S.C. 404, IRS Publication 560, SECURE 2.0 Act",
    applicableEntityTypes: ["1120S", "1065", "C-Corp"],
    triggerOn: ["has_net_profit", "has_employees"],
    excludeIf: ["business_has_loss"],
    category: "Retirement Planning",
  },
  {
    id: "roth_401k_business",
    name: "Roth 401k (Business)",
    shortDescription: "An employee-based retirement plan with after-tax contributions and tax-free growth for retirement.",
    longDescription: "Employer-sponsored Roth 401(k) allows after-tax employee contributions that grow and are withdrawn tax-free. Employer matching contributions go to traditional (pre-tax) side. Valuable for employees expecting higher future tax rates. No income limits unlike Roth IRA.",
    savingsMin: 0,
    savingsMax: 52500,
    irsRefs: "26 U.S.C. 402A, 26 U.S.C. 414(v), IRS Notice 2024-02, SECURE 2.0 Act 604, IRS Publication 560",
    applicableEntityTypes: ["1120S", "1065", "C-Corp"],
    triggerOn: ["has_net_profit", "has_employees"],
    excludeIf: ["business_has_loss"],
    category: "Retirement Planning",
  },
  {
    id: "late_s_election",
    name: "Late S Corporation Election",
    shortDescription: "Request for S corporation tax treatment after standard deadline.",
    longDescription: "Partnerships and C corporations with net income above approximately $50,000 may benefit from S-Corp election to eliminate self-employment taxes on distributions. Revenue Procedure 2013-30 allows late elections in many circumstances. Owner must pay reasonable salary while taking remaining profits as distributions.",
    savingsMin: 5000,
    savingsMax: 20000,
    irsRefs: "26 U.S.C. 6699, IRS Form 1120-S, Form 2553, Revenue Procedure 2013-30, Revenue Procedure 84-35, Chief Counsel Advice 201333008",
    applicableEntityTypes: ["1065", "1040"],
    triggerOn: ["is_partnership_or_schedule_c", "business_net_profit_over_50k"],
    excludeIf: ["is_s_corp", "is_c_corp"],
    category: "Legal Entity Optimization",
  },
  {
    id: "late_c_election",
    name: "Late C Corporation Election",
    shortDescription: "Request for C corporation tax treatment after standard deadline.",
    longDescription: "C corporations pay a flat 21% federal tax rate, significantly lower than individual rates for high-income earners retaining profits in the business. Best for businesses with income above $100,000 that reinvest profits rather than distributing them. Eliminates pass-through taxation on retained earnings.",
    savingsMin: 5000,
    savingsMax: 20000,
    irsRefs: "26 U.S.C. 6651, 26 U.S.C. 6699, IRS Form 1120, Revenue Procedure 84-35, IRS Publication 542",
    applicableEntityTypes: ["1120S", "1065"],
    triggerOn: ["business_net_profit_over_100k"],
    excludeIf: ["is_c_corp", "business_has_loss"],
    category: "Legal Entity Optimization",
  },
  {
    id: "employee_achievement_award",
    name: "Employee Achievement Award",
    shortDescription: "Tax-free tangible awards for employee service or safety achievements.",
    longDescription: "Qualified employee achievement awards (QEAAP) are tangible personal property given for length of service or safety achievements. Up to $1,600 per employee per year is deductible by the employer and tax-free to the employee. Must be part of a formal written plan. Cash, gift cards, and vacation are excluded.",
    savingsMin: 2100,
    savingsMax: 6720,
    irsRefs: "IRC 74(c), IRC 274(j), IRC 162(a), Treas. Reg. 1.74-1(c), IRS Publication 15-B, IRS Publication 535",
    applicableEntityTypes: ["1120S", "1065", "C-Corp"],
    triggerOn: ["has_employees", "has_net_profit"],
    excludeIf: ["business_has_loss"],
    category: "Maximize Deductions",
  },
  {
    id: "health_reimbursement",
    name: "Health Reimbursement Arrangement (HRA)",
    shortDescription: "An employer-funded account that reimburses you tax-free for your medical expenses.",
    longDescription: "HRAs allow businesses to reimburse employees for qualified medical expenses tax-free to both employer and employee. QSEHRA (for businesses with fewer than 50 employees) allows up to $6,150 individual / $12,450 family reimbursement annually. ICHRA has no limits. S-Corp owners with >2% ownership must include health premiums in W-2.",
    savingsMin: 2000,
    savingsMax: 7500,
    irsRefs: "IRC 105, IRC 106, IRC 4980G, Treas. Reg. 1.105-2, IRS Notice 2019-45, IRS Publication 969, IRS Publication 502",
    applicableEntityTypes: ["1065", "C-Corp"],
    triggerOn: ["has_non_owner_employees"],
    excludeIf: ["is_s_corp"],
    category: "Insurance",
  },
  {
    id: "qualified_edu_assistance",
    name: "Qualified Educational Assistance Program",
    shortDescription: "Employer-provided tax-free educational benefits for employees.",
    longDescription: "Section 127 allows employers to provide up to $5,250 per year per employee in tax-free educational assistance. Benefits are deductible by the employer and tax-free to the employee. Can include undergraduate, graduate, or job-related courses. Requires a formal written plan.",
    savingsMin: 2000,
    savingsMax: 10000,
    irsRefs: "26 U.S.C. 127, 26 U.S.C. 117, 26 U.S.C. 162, IRS Notice 2024-22, IRS Publication 15-B, 26 C.F.R. 1.127-2",
    applicableEntityTypes: ["1120S", "1065", "C-Corp"],
    triggerOn: ["has_non_owner_employees"],
    excludeIf: [],
    category: "Fringe Benefits",
  },
  {
    id: "work_opportunity_credit",
    name: "Work Opportunity Tax Credit (WOTC)",
    shortDescription: "Employer tax credit for hiring from specific groups facing employment barriers.",
    longDescription: "Federal tax credit for hiring individuals from 10 target groups including veterans, ex-felons, SNAP recipients, and vocational rehabilitation referrals. Credit is 25-40% of first-year wages up to $6,000 (up to $9,600 for some veterans). Must certify new hires with state workforce agency on Form 8850.",
    savingsMin: 1000,
    savingsMax: 20000,
    irsRefs: "26 U.S.C. 51, Consolidated Appropriations Act 2021, IRS Form 8850, IRS Form 5884, IRS Notice 2024-45",
    applicableEntityTypes: ["1120S", "1065", "C-Corp"],
    triggerOn: ["has_employees"],
    excludeIf: [],
    category: "Tax Credits",
  },
  {
    id: "maximize_depreciation",
    name: "Maximize Depreciation (Section 179 / Bonus)",
    shortDescription: "Immediately deduct the full cost of qualifying business assets instead of depreciating over years.",
    longDescription: "Section 179 allows immediate expensing of up to $1,160,000 (2023) in qualifying business assets. Bonus depreciation (60% in 2024, phasing down) allows additional first-year deductions. Particularly powerful for businesses purchasing equipment, computers, furniture, and qualifying vehicles.",
    savingsMin: 5000,
    savingsMax: 50000,
    irsRefs: "26 U.S.C. 179, 26 U.S.C. 168(k), IRS Form 4562, IRS Publication 946, TCJA Bonus Depreciation Rules",
    applicableEntityTypes: ["1120S", "1065", "C-Corp", "1040"],
    triggerOn: ["has_business_income", "has_net_profit"],
    excludeIf: [],
    category: "Maximize Deductions",
  },
  {
    id: "cost_segregation",
    name: "Cost Segregation",
    shortDescription: "Accelerate depreciation on commercial real estate by reclassifying components to shorter asset lives.",
    longDescription: "A cost segregation study reclassifies building components into 5, 7, and 15-year property categories that qualify for accelerated depreciation and bonus depreciation. Can generate significant first-year deductions for real estate investors. Most cost-effective for buildings over $1M in value.",
    savingsMin: 10000,
    savingsMax: 100000,
    irsRefs: "IRC 168, 26 U.S.C. 168(k), IRS Cost Segregation Audit Techniques Guide, Rev. Proc. 87-56",
    applicableEntityTypes: ["1040", "1065", "C-Corp"],
    triggerOn: ["has_real_property", "has_real_estate"],
    excludeIf: [],
    category: "Niche Strategies",
  },
  {
    id: "captive_insurance",
    name: "Captive Insurance",
    shortDescription: "An insurance company you own that insures risks of your operating businesses.",
    longDescription: "A captive insurance company allows businesses to self-insure against risks and deduct premiums paid as business expenses. Reserves accumulate tax-free and excess reserves are taxed at capital gains rates when distributed. Best for businesses with consistent profitability and significant insurable risks.",
    savingsMin: 15000,
    savingsMax: 50000,
    irsRefs: "IRC 831(b), IRC 162, IRS Notice 2016-66, Rev. Rul. 2005-40, IRS Audit Techniques Guide for Captive Insurance",
    applicableEntityTypes: ["1120S", "1065", "C-Corp"],
    triggerOn: ["has_net_profit", "business_net_profit_over_100k"],
    excludeIf: [],
    category: "Insurance",
  },
  {
    id: "section_199a",
    name: "Section 199A (QBI Deduction)",
    shortDescription: "Up to 20% deduction on qualified business income from pass-through entities.",
    longDescription: "Pass-through business owners may deduct up to 20% of qualified business income. Subject to income limitations above $315,000 MFJ ($157,500 single) and industry restrictions for certain service businesses. W-2 wage and capital basis limitations apply at higher income levels.",
    savingsMin: 5000,
    savingsMax: 40000,
    irsRefs: "IRC 199A, Treas. Reg. 1.199A-1 through 1.199A-6, IRS Publication 535",
    applicableEntityTypes: ["1120S", "1065", "1040"],
    triggerOn: ["has_business_income", "has_net_profit"],
    excludeIf: ["is_c_corp"],
    category: "Tax Cuts & Jobs Act",
  },
  {
    id: "profit_sharing",
    name: "Profit Sharing Plan",
    shortDescription: "Employer contributions to employee retirement accounts based on business profits.",
    longDescription: "Profit sharing plans allow businesses to contribute up to 25% of employee compensation (up to $66,000 total in 2023) to employee retirement accounts. Contributions are discretionary and fully deductible. Can be combined with 401(k) plans to maximize retirement savings.",
    savingsMin: 5000,
    savingsMax: 66000,
    irsRefs: "26 U.S.C. 401(a), 26 U.S.C. 404, IRS Publication 560, IRS Form 5500",
    applicableEntityTypes: ["1120S", "1065", "C-Corp"],
    triggerOn: ["has_net_profit", "has_employees"],
    excludeIf: ["business_has_loss"],
    category: "Retirement Planning",
  },
  {
    id: "cash_balance_plan",
    name: "Cash Balance / Defined Benefit Plan",
    shortDescription: "A pension-style retirement plan that allows high contributions for older, high-income business owners.",
    longDescription: "Cash balance plans can allow annual contributions of $100,000-$300,000+ depending on age, providing massive pre-tax retirement savings. Most valuable for business owners 45+ with high income and no or few employees. Often combined with 401(k) profit sharing for maximum benefit.",
    savingsMin: 30000,
    savingsMax: 200000,
    irsRefs: "26 U.S.C. 412, IRC 414(j), IRS Publication 560, SECURE 2.0 Act, Rev. Proc. 2022-40",
    applicableEntityTypes: ["1120S", "1065", "C-Corp"],
    triggerOn: ["has_net_profit", "business_net_profit_over_100k"],
    excludeIf: ["business_has_loss"],
    category: "Retirement Planning",
  },
  {
    id: "deferred_compensation",
    name: "Deferred Compensation",
    shortDescription: "Arrange to defer a portion of compensation to a future tax year.",
    longDescription: "Non-qualified deferred compensation (NQDC) arrangements allow executives and highly compensated employees to defer salary or bonuses to future years, typically retirement when in a lower bracket. Must comply with IRC 409A distribution rules.",
    savingsMin: 5000,
    savingsMax: 30000,
    irsRefs: "IRC 409A, IRC 457, IRS Notice 2005-1, Treas. Reg. 1.409A-1 through 1.409A-6",
    applicableEntityTypes: ["1120S", "C-Corp"],
    triggerOn: ["has_wages", "has_net_profit"],
    excludeIf: [],
    category: "Advanced Strategies",
  },
  {
    id: "1031_exchange",
    name: "1031 Like-Kind Exchange",
    shortDescription: "Defer capital gains taxes indefinitely by exchanging investment real estate for like-kind property.",
    longDescription: "IRC 1031 allows investors to sell investment real estate and reinvest proceeds in a like-kind property while deferring capital gains taxes indefinitely. Must identify replacement property within 45 days and close within 180 days. A qualified intermediary is required.",
    savingsMin: 10000,
    savingsMax: 100000,
    irsRefs: "26 U.S.C. 1031, Treas. Reg. 1.1031(a)-1, Rev. Proc. 2010-14, IRS Publication 544",
    applicableEntityTypes: ["1040", "1065", "C-Corp"],
    triggerOn: ["has_real_property", "has_real_estate"],
    excludeIf: [],
    category: "Niche Strategies",
  },
  {
    id: "charitable_remainder_trust",
    name: "Charitable Remainder Trust (CRT)",
    shortDescription: "Donate appreciated assets to a trust, receive income stream, and get a charitable deduction.",
    longDescription: "A CRT allows donors to contribute appreciated assets, receive a partial charitable deduction, get an income stream for life or a term of years, and ultimately benefit a charity. Avoids immediate capital gains on appreciated assets. Best for high-net-worth individuals with charitable intent.",
    savingsMin: 10000,
    savingsMax: 75000,
    irsRefs: "IRC 664, IRC 170, IRC 4947, Treas. Reg. 1.664-1 through 1.664-4, IRS Publication 561",
    applicableEntityTypes: ["1040"],
    triggerOn: ["has_long_term_capital_gains", "agi_over_400k"],
    excludeIf: [],
    category: "Gift & Estate Planning",
  },
  {
    id: "opportunity_zone",
    name: "Opportunity Zone Investment",
    shortDescription: "Defer and potentially reduce capital gains taxes by investing in Qualified Opportunity Funds.",
    longDescription: "Investing capital gains in a Qualified Opportunity Fund (QOF) allows deferral of taxes until 2026 or disposition. After 10 years of holding, appreciation in the QOF investment is excluded from tax entirely. Powerful for taxpayers with large capital gains seeking long-term tax-efficient growth.",
    savingsMin: 5000,
    savingsMax: 50000,
    irsRefs: "IRC 1400Z-2, Treas. Reg. 1.1400Z-2, IRS Form 8997, Opportunity Zone Tax Credit",
    applicableEntityTypes: ["1040", "C-Corp"],
    triggerOn: ["has_capital_gains", "has_long_term_capital_gains"],
    excludeIf: [],
    category: "Tax Cuts & Jobs Act",
  },
];

// Strategy lookup by ID
export const STRATEGY_MAP = Object.fromEntries(STRATEGIES.map(s => [s.id, s]));

// Get strategies applicable to a given entity type
export function getStrategiesForEntityType(entityType: EntityType): Strategy[] {
  return STRATEGIES.filter(s => s.applicableEntityTypes.includes(entityType));
}

// Auto-suggest logic: returns {suggested, excluded} based on trigger keys present
export function autoSuggestStrategies(
  entityType: EntityType,
  triggers: Set<TriggerKey>
): { suggested: Strategy[]; excluded: Strategy[] } {
  const applicable = getStrategiesForEntityType(entityType);
  const suggested: Strategy[] = [];
  const excluded: Strategy[] = [];

  for (const strategy of applicable) {
    const isExcluded = strategy.excludeIf.some(k => triggers.has(k));
    const isTriggered = strategy.triggerOn.length === 0 || strategy.triggerOn.some(k => triggers.has(k));

    if (isExcluded) {
      excluded.push(strategy);
    } else if (isTriggered) {
      suggested.push(strategy);
    } else {
      excluded.push(strategy);
    }
  }

  return { suggested, excluded };
}
